[package]
name = "ds"
version = "0.1.0"
authors = ["Leonz Chang <bellerophon00530@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ds-core = { path = "../../core" }

tonic = "0.8.2"
futures = "0.3.25"
once_cell = "1.13.0"
rand = "0.8.5"
clap = { version ="4.0.22", features = ["derive", "env", "cargo"] }
strum = "0.24.1"
strum_macros = "0.24.3"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
anyhow = "1.0.66"
log = "0.4.17"
env_logger = "0.9.3"
ansi_term = "0.12.1"
chrono = { version = "0.4.22", features = ["serde"] }
tokio = { version = "1.21.2", features = ["signal", "rt-multi-thread", "net", "time", "macros", "sync"] }
actix-web = { version = "4.2.1", default-features = false, features = ["macros"] }
actix-cors = "0.6.4"
actix-session = "0.7.2"
protobuf = "3.2.0"
http = "0.2.8"
