[package]
name = "ds-auth-grpc"
version = "0.1.0"
authors = ["Leonz Chang <bellerophon00530@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ds-core = { path = "../../core" }

tonic = "0.8.2"
uuid = { version = "1.2.1",features = [ "v4", "fast-rng", "macro-diagnostics"]}
sha2 = "0.10.6"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.16"
clap = { version ="4.0.22", features = ["derive", "env", "cargo"] }
strum = "0.24.1"
strum_macros = "0.24.3"
serde = { version = "1.0.147", features = ["derive"] }
anyhow = "1.0.66"
log = "0.4.17"
